Assignments 1 submitted by Karthik.N

1.Split the string

In [2]:
s = "Hello There!!"
s.split()

['Hello', 'There!!']

In [4]:
planetvar = "Earth"
diametervar = "12742"

2. Use format to print the string

In [7]:
print ("The diameter of {planet} is {diameter} kilometers.".format(planet=planetvar,diameter=diametervar))

The diameter of Earth is 12742 kilometers.


3. In the nest dictionart grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
t = d['k1'][3]['tricky'][3]['target'][3]
print(t)

hello


4. Numpy

In [13]:
import numpy as np
ap = np.zeros(10)
ap

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
b=np.array([5,5,5,5,5,5,5,5,5,5])
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

5. Create an array of all the even integers from 20 to 35

In [16]:
e = np.arange(20,35,2)
e

array([20, 22, 24, 26, 28, 30, 32, 34])

6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])


7. Concatenate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

Pandas

8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd
data={'col1':['Apple','Mango','Banana'],'col2':['Grapes','Guava','Orange']}
df=pd.DataFrame(data)
df

col1    col2
0   Apple  Grapes
1   Mango   Guava
2  Banana  Orange

9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
d = pd.date_range('2023-01-01','2023-02-10')
d

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24